spring.application.name=dgac-ms-usuarios

# Railway/Render inyectarán su propio puerto aquí. Si no existe (en tu PC local), usará 8081.
server.port=${PORT:8081}

# Usamos variables de entorno. Lo que está después de los dos puntos (:) es el valor por defecto que usará en tu PC.
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-aged-cloud-aqdbd64c-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_t9MGlKdf0DTv}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true