spring.application.name=dgac-ms-usuarios
server.port=8081

spring.datasource.url=jdbc:postgresql://ep-aged-cloud-aqdbd64c-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_t9MGlKdf0DTv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true